<?php

/**
 * @file
 * Date formats to be included to the installation and main module file.
 *
 * This is necessary so we can call these constants during the installation
 * as well as during the execution of other module functions.
 *
 * Created by: Topsitemakers
 * http://www.topsitemakers.com/
 */

define('BOILERPLATE_DATE_FORMAT_SAMPLE', 'F j, Y \a\t g:i a');
define('BOILERPLATE_DATE_LABEL_SAMPLE', 'Boilerplate: sample date format');
define('BOILERPLATE_DATE_TYPE_SAMPLE', 'boilerplate_date_format_sample');
